<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<!-- GENERAL INFORMATION -->
	<artifactId>compss-tests-fault_tolerance</artifactId>
	<packaging>pom</packaging>
	<parent>
		<groupId>es.bsc.compss.tests</groupId>
		<artifactId>compss-tests</artifactId>
		<version>3.1.rc2305</version>
		<relativePath>..</relativePath>
	</parent>

	<!-- PROJECT INFORMATION -->
	<name>COMPSs Framework Test - Fault Tolerance</name>
	<description>COMPSs Framework Tests - Fault Tolerance</description>
	<url>http://compss.bsc.es</url>
	<inceptionYear>2014</inceptionYear>
	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</licenses>
	<organization>
		<name>BSC</name>
		<url>http://www.bsc.es</url>
	</organization>

	<!-- SUB-MODULES -->
	<modules>
        <module>0_error_manager_all_blocked</module>
        <module>0_error_manager_no_in_file</module>
        <module>0_error_manager_reschedule_fail</module>
        <module>2_no_empty_constructor</module>
		<module>2_on_failure_retry</module>
		<!-- 2_on_failure_retry_python -->
		<module>2_on_failure_cancel_successors</module>
		<!-- 2_on_failure_cancel_successors -->
		<module>2_on_failure_ignore</module>
		<!-- 2_on_failure_ignore_python -->
		<module>2_on_failure_fail</module>
		<!-- 2_on_failure_fail_python -->
		<module>2_on_failure_in_out</module>
		<!-- 1_exceptions_after_sync -->
		<!-- 1_exceptions_before_sync -->
		<!-- 1_exceptions_before_tasks -->
		<!-- 1_exceptions_in_worker -->
		<!-- Add new modules below -->
	</modules>
</project>
